Beets 23 export indivdual assets
bee-cs458/bee-tracking-software pull request #119
Opened 2023-05-01 19:51 UTC by hessd6187

### Definition of Done:

* [YUP] Have you checked your [Jira](https://bee-cs458.atlassian.net/jira/software/projects/BEETS/boards/2/backlog) task, to make sure the user acceptance criteria are met?
* [YUP] Does your code have comments describing its function and reason?

### Source Control

* [YUP] Is all relevant code checked-in?
* [YUP] Is this branch ready to be reviewed by the Tech Lead?

### Formatting

* [YUP] Do your variable names make sense (to others)?
* [YUP] Have you removed unnecessary Console.logs? 
* [THINK SO] Is your code style consistent with other code in the file or the [Style Guide](https://google.github.io/styleguide/jsguide.html)

2023-05-01 19:59 UTC, levertyk requested changes

2023-05-01 19:59 UTC, levertyk commented on client/src/routes/SingleAssetPage/SingleAssetPage.js
> +          <input type="text" value={csvName} onChange={(e) => setCsvName(e.target.value)} />
Maybe just get the csvName without ".csv" then add csv right before saving. That way we can make sure users are only downloading csv files:
<img width="571" alt="Screenshot 2023-05-01 at 2 54 54 PM" src="https://user-images.githubusercontent.com/91560030/235520391-7869e17b-251d-45c0-8756-e7d8544f7f74.png">

<img width="627" alt="Screenshot 2023-05-01 at 2 55 22 PM" src="https://user-images.githubusercontent.com/91560030/235520375-18ad6c25-7253-4eda-8a35-8c050745f8df.png">

2023-05-01 20:13 UTC, hessd6187 commented
Should be fixed

2023-05-03 15:44 UTC, levertyk approved these changes
Changes Approved

2023-05-03 15:45 UTC, merged