Beets 433 add asset convert to react
bee-cs458/bee-tracking-software pull request #82
Opened 2023-04-02 20:29 UTC by levertyk

### Definition of Done:

* [ ] Have you checked your [Jira](https://bee-cs458.atlassian.net/jira/software/projects/BEETS/boards/2/backlog) task, to make sure the user acceptance criteria are met?
* [ ] Does your code have comments describing its function and reason?

### Tests

* [ ] Do you have Jest tests?
* [ ] Have you documented your testing criteria and edge cases in your Jira task?

### Source Control

* [ ] Is all relevant code checked-in?
* [ ] Is this branch ready to be reviewed by the Tech Lead?

### Formatting

* [ ] Do your variable names make sense (to others)?
* [ ] Have you removed unnecessary Console.logs? 
* [ ] Is your code style consistent with other code in the file or the [Style Guide](https://google.github.io/styleguide/jsguide.html)

2023-04-02 20:31 UTC, levertyk commented
Just look at the add asset file, the other changes were all removing unused variables/imports and just hitting the format button to get rid of 4spaces=tab.

2023-04-02 22:21 UTC, piratecody commented
Please resolve the conflict, then I can review

2023-04-03 15:12 UTC, piratecody requested changes
There is one more conflict, I would fix it myself but I don't wanna risk breaking anything

2023-04-03 15:13 UTC, piratecody approved these changes

2023-04-03 15:14 UTC, merged