Beets 447 single asset pages design
bee-cs458/bee-tracking-software pull request #95
Opened 2023-04-11 06:08 UTC by piratecody

### Definition of Done:

* [X] Have you checked your [Jira](https://bee-cs458.atlassian.net/jira/software/projects/BEETS/boards/2/backlog) task, to make sure the user acceptance criteria are met?
* [X] Does your code have comments describing its function and reason?

### Source Control

* [X] Is all relevant code checked-in?
* [X] Is this branch ready to be reviewed by the Tech Lead?

### Formatting

* [X] Do your variable names make sense (to others)?
* [X] Have you removed unnecessary Console.logs? 
* [X] Is your code style consistent with other code in the file or the [Style Guide](https://google.github.io/styleguide/jsguide.html)

2023-04-11 16:19 UTC, levertyk requested changes
When I log in as an operator, and select an asset from the list, the page crashes.
<img width="855" alt="Screenshot 2023-04-11 at 11 09 05 AM" src="https://user-images.githubusercontent.com/91560030/231223745-b6f4dff4-74e5-42bd-add0-78c56cd1f2cc.png">
<img width="858" alt="Screenshot 2023-04-11 at 11 09 23 AM" src="https://user-images.githubusercontent.com/91560030/231223755-70e16dd1-851f-4131-aa13-a5d37d7af636.png">

2023-04-11 16:21 UTC, levertyk commented
> When I log in as an operator, and select an asset from the list, the page crashes. <img alt="Screenshot 2023-04-11 at 11 09 05 AM" width="855" src="https://user-images.githubusercontent.com/91560030/231223745-b6f4dff4-74e5-42bd-add0-78c56cd1f2cc.png"> <img alt="Screenshot 2023-04-11 at 11 09 23 AM" width="858" src="https://user-images.githubusercontent.com/91560030/231223755-70e16dd1-851f-4131-aa13-a5d37d7af636.png">

The same thing happens as an owner.

2023-04-12 15:08 UTC, piratecody commented
> > When I log in as an operator, and select an asset from the list, the page crashes. <img alt="Screenshot 2023-04-11 at 11 09 05 AM" width="855" src="https://user-images.githubusercontent.com/91560030/231223745-b6f4dff4-74e5-42bd-add0-78c56cd1f2cc.png"> <img alt="Screenshot 2023-04-11 at 11 09 23 AM" width="858" src="https://user-images.githubusercontent.com/91560030/231223755-70e16dd1-851f-4131-aa13-a5d37d7af636.png">
> 
> The same thing happens as an owner.

@levertyk I can't seem to replicate the issue. Could you let me know what asset you were trying to view?

2023-04-12 15:09 UTC, piratecody commented on client/src/components/AssetTable/AssetRow/AssetRow.js
> +      <td><Link to={`/asset/${asset.asset_tag}`} state={{ asset, categoryLabel }}>{asset.asset_tag}</Link></td>
I can't replicate this either :/

2023-04-12 15:24 UTC, piratecody commented
@levertyk I may have found the issue & patched it. please try again

2023-04-12 15:31 UTC, levertyk commented
> @levertyk I may have found the issue & patched it. please try again

@piratecody 
I'm still getting issues, but now with more error messages. It happens on all assets, or at least the 8 assets I checked.

<img width="859" alt="Screenshot 2023-04-12 at 10 28 21 AM" src="https://user-images.githubusercontent.com/91560030/231507155-b69da1fa-b67d-4af9-97fe-d9929119938d.png">
<img width="823" alt="Screenshot 2023-04-12 at 10 28 12 AM" src="https://user-images.githubusercontent.com/91560030/231507173-97fa1a2d-4dbf-4563-876c-46e7d76c2001.png">

2023-04-12 15:35 UTC, piratecody commented
> > @levertyk I may have found the issue & patched it. please try again
> 
> @piratecody I'm still getting issues, but now with more error messages. It happens on all assets, or at least the 8 assets I checked.
> 
> <img alt="Screenshot 2023-04-12 at 10 28 21 AM" width="859" src="https://user-images.githubusercontent.com/91560030/231507155-b69da1fa-b67d-4af9-97fe-d9929119938d.png">
> 
> <img alt="Screenshot 2023-04-12 at 10 28 12 AM" width="823" src="https://user-images.githubusercontent.com/91560030/231507173-97fa1a2d-4dbf-4563-876c-46e7d76c2001.png">

I do see one issue - currently only owners can see checkout records. Do we want operators to be able to see the checkout history?

2023-04-12 15:39 UTC, piratecody commented
> @piratecody Yeah, they should. Was that hard coded into the API call?

Yeah, the api endpoint to get all checkout records is restricted to owners right now. I can change that and some of the errors should clear up.

2023-04-12 15:44 UTC, piratecody commented
> > > @piratecody Yeah, they should. Was that hard coded into the API call?
> > 
> > 
> > Yeah, the api endpoint to get all checkout records is restricted to owners right now. I can change that and some of the errors should clear up.
> 
> Yeah, let's do that. I think that was just a logical error then.

Alright changed that. Also, the reason the cart column is so big for operators is that the edit asset column doesn't appear for them, so the columns expand to fill the space (I think)

2023-04-12 15:44 UTC, levertyk approved these changes

2023-04-12 15:45 UTC, merged